In [1]:
import pandas as pd
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import pyplot
import statsmodels.api as sm
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.stattools import adfuller
from statsmodels.graphics.tsaplots import plot_acf,plot_pacf
import itertools
import math
from statsmodels.tsa.arima_model import ARIMA
from pandas.plotting import autocorrelation_plot
%matplotlib inline

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [0]:
df=pd.read_csv('/content/train (9).csv')

In [4]:
df.head()

        Territory X Date  target  cases    Territory     Date
0  Afghanistan X 1/22/20       0      0  Afghanistan  1/22/20
1  Afghanistan X 1/23/20       0      0  Afghanistan  1/23/20
2  Afghanistan X 1/24/20       0      0  Afghanistan  1/24/20
3  Afghanistan X 1/25/20       0      0  Afghanistan  1/25/20
4  Afghanistan X 1/26/20       0      0  Afghanistan  1/26/20

In [44]:

import warnings
from pandas import read_csv
from statsmodels.tsa.arima_model import ARIMA
from sklearn.metrics import mean_squared_error
 
# evaluate an ARIMA model for a given order (p,d,q)
def evaluate_arima_model(X, arima_order):
	# prepare training dataset
	train_size = int(len(X) * 0.66)
	train, test = X[0:train_size], X[train_size:]
	history = [x for x in train]
	# make predictions
	predictions = list()
	for t in range(len(test)):
		model = ARIMA(history, order=arima_order)
		model_fit = model.fit(disp=0)
		yhat = model_fit.forecast()[0]
		predictions.append(yhat)
		history.append(test[t])
	# calculate out of sample error
	error = mean_squared_error(test, predictions)
	return error
 
# evaluate combinations of p, d and q values for an ARIMA model
def evaluate_models(dataset, p_values, d_values, q_values):
	dataset = dataset.astype('float32')
	best_score, best_cfg = float("inf"), None
	for p in p_values:
		for d in d_values:
			for q in q_values:
				order = (p,d,q)
				try:
					mse = evaluate_arima_model(dataset, order)
					if mse < best_score:
						best_score, best_cfg = mse, order
					print('ARIMA%s MSE=%.3f' % (order,mse))
				except:
					continue
	return best_cfg

def preidct (best,series,n):
        
        series = series.astype('float32')
        model = ARIMA(series, order=best)
        
      
        model_fit = model.fit(disp=0)
        output = model_fit.forecast(steps=n)
        yhat = output[0]


        return(yhat)

def verif(i):
		#if (str(i)=='United States of America (the)') or ((str(i)=='Switzerland')) or (str(i)=='United Kingdom of Great Britain and Northern Ireland (the)') or (str(i)=='France')  : 
		     #nstep=64     w
		#elif ((str(i)=='Germany'))  :
			   #nstep=43		 
		#elif (str(i)=='Spain') or ((str(i)=='Belgium'))  :
		     #nstep=30
		if (str(i)=='United Kingdom of Great Britain and Northern Ireland (the)')  :
			   nstep=37	 
		else : 
		     nstep=7

		return nstep


predictions=[]

p_values = [0, 1, 2,3]
d_values = range(0, 3)
q_values = range(0, 3) 
warnings.filterwarnings("ignore")
# load dataset
for i in df['Territory'].unique():
    
  nstep=59
  x=df.loc[df['Territory']==i]
  x=x[['Date','target']]
  x.index=x['Date']
  x=x.drop(columns=['Date'])
  series = x
  best=evaluate_models(series.values,p_values,d_values,q_values)
  print(best)

  yhat=preidct(best,series.values,nstep)
  for k in yhat[0:nstep] :
    predictions.append(k)

ARIMA(0, 0, 0) MSE=32.480
ARIMA(0, 1, 0) MSE=1.281
ARIMA(0, 2, 0) MSE=1.690
(0, 1, 0)
ARIMA(0, 0, 0) MSE=125.468
ARIMA(0, 0, 1) MSE=35.564
ARIMA(0, 1, 0) MSE=1.475
ARIMA(0, 1, 1) MSE=1.768
ARIMA(0, 1, 2) MSE=1.752
ARIMA(0, 2, 0) MSE=2.142
ARIMA(0, 2, 1) MSE=1.153
ARIMA(1, 0, 0) MSE=1.747
ARIMA(1, 1, 0) MSE=1.586
ARIMA(1, 2, 0) MSE=1.911
ARIMA(2, 0, 0) MSE=2.007
ARIMA(2, 1, 0) MSE=1.620
ARIMA(2, 2, 0) MSE=1.579
ARIMA(3, 0, 0) MSE=1.748
ARIMA(3, 1, 0) MSE=1.590
ARIMA(3, 2, 0) MSE=1.151
(3, 2, 0)
ARIMA(0, 0, 0) MSE=7486.078
ARIMA(0, 0, 1) MSE=2122.600
ARIMA(0, 1, 0) MSE=142.721
ARIMA(0, 1, 1) MSE=77.133
ARIMA(0, 2, 0) MSE=30.019
ARIMA(0, 2, 1) MSE=32.576
ARIMA(0, 2, 2) MSE=33.207
ARIMA(1, 0, 0) MSE=167.913
ARIMA(1, 1, 0) MSE=31.411
ARIMA(1, 2, 0) MSE=37.668
ARIMA(2, 1, 0) MSE=41.385
(0, 2, 0)
ARIMA(0, 0, 0) MSE=115.829
ARIMA(0, 1, 0) MSE=1.841
ARIMA(0, 2, 0) MSE=1.427
(0, 2, 0)
ARIMA(0, 0, 0) MSE=1.529
ARIMA(0, 1, 0) MSE=0.148
ARIMA(0, 2, 0) MSE=0.301
(0, 1, 0)
ARIMA(0, 0, 0) MSE=0.326
ARIMA(0, 1, 0) MSE=0.073
ARIMA(0, 2, 0) MSE=0.075
(0, 1, 0)
ARIMA(0, 0, 0) MSE=750.610
ARIMA(0, 0, 1) MSE=209.918
ARIMA(0, 1, 0) MSE=12.003
ARIMA(0, 1, 1) MSE=9.297
ARIMA(0, 1, 2) MSE=9.701
ARIMA(0, 2, 0) MSE=6.275
ARIMA(0, 2, 1) MSE=4.514
ARIMA(1, 0, 0) MSE=14.422
ARIMA(1, 1, 0) MSE=6.683
ARIMA(1, 2, 0) MSE=5.050
ARIMA(2, 1, 0) MSE=6.034
ARIMA(2, 2, 0) MSE=5.242
ARIMA(3, 1, 0) MSE=5.925
(0, 2, 1)
ARIMA(0, 0, 0) MSE=17.717
ARIMA(0, 1, 0) MSE=0.628
ARIMA(0, 2, 0) MSE=1.014
(0, 1, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=418.434
ARIMA(0, 0, 1) MSE=130.823
ARIMA(0, 1, 0) MSE=5.516
ARIMA(0, 1, 1) MSE=4.169
ARIMA(0, 1, 2) MSE=4.080
ARIMA(0, 2, 0) MSE=3.647
ARIMA(0, 2, 1) MSE=2.530
ARIMA(1, 0, 0) MSE=6.714
ARIMA(1, 1, 0) MSE=3.383
ARIMA(1, 2, 0) MSE=3.058
ARIMA(2, 0, 0) MSE=4.056
ARIMA(2, 1, 0) MSE=3.109
ARIMA(2, 2, 0) MSE=2.806
ARIMA(2, 2, 1) MSE=2.786
ARIMA(3, 0, 0) MSE=3.153
ARIMA(3, 1, 0) MSE=2.913
ARIMA(3, 2, 0) MSE=2.817
ARIMA(3, 2, 1) MSE=2.987
(0, 2, 1)
ARIMA(0, 0, 0) MSE=14556.266
ARIMA(0, 0, 1) MSE=4109.725
ARIMA(0, 1, 0) MSE=156.805
ARIMA(0, 1, 1) MSE=79.299
ARIMA(0, 1, 2) MSE=79.551
ARIMA(0, 2, 0) MSE=31.352
ARIMA(0, 2, 1) MSE=26.402
ARIMA(1, 0, 0) MSE=199.128
ARIMA(1, 1, 0) MSE=35.127
ARIMA(1, 2, 0) MSE=31.254
(0, 2, 1)
ARIMA(0, 0, 0) MSE=14.882
ARIMA(0, 0, 1) MSE=4.954
ARIMA(0, 1, 0) MSE=0.337
ARIMA(0, 1, 1) MSE=0.392
ARIMA(0, 1, 2) MSE=0.376
ARIMA(0, 2, 0) MSE=0.677
ARIMA(0, 2, 1) MSE=0.330
ARIMA(1, 0, 0) MSE=0.415
ARIMA(1, 1, 0) MSE=0.361
ARIMA(1, 2, 0) MSE=0.456
ARIMA(2, 0, 0) MSE=0.448
ARIMA(2, 1, 0) MSE=0.353
ARIMA(2, 2, 0) MSE=0.466
ARIMA(3, 0, 0) MSE=0.440
ARIMA(3, 1, 0) MSE=0.381
ARIMA(3, 2, 0) MSE=0.484
ARIMA(3, 2, 1) MSE=0.468
(0, 2, 1)
ARIMA(0, 0, 0) MSE=7.192
ARIMA(0, 1, 0) MSE=0.495
ARIMA(0, 2, 0) MSE=0.788
(0, 1, 0)
ARIMA(0, 0, 0) MSE=8.453
ARIMA(0, 1, 0) MSE=0.176
ARIMA(0, 2, 0) MSE=0.301
(0, 1, 0)
ARIMA(0, 0, 0) MSE=53.966
ARIMA(0, 1, 0) MSE=1.853
ARIMA(0, 2, 0) MSE=1.089
(0, 2, 0)
ARIMA(0, 0, 0) MSE=1.132
ARIMA(0, 1, 0) MSE=0.108
ARIMA(0, 2, 0) MSE=0.075
(0, 2, 0)
ARIMA(0, 0, 0) MSE=30.394
ARIMA(0, 1, 0) MSE=1.754
ARIMA(0, 2, 0) MSE=1.835
(0, 1, 0)
ARIMA(0, 0, 0) MSE=841731.281
ARIMA(0, 0, 1) MSE=241446.957
ARIMA(0, 1, 0) MSE=15608.651
ARIMA(0, 1, 1) MSE=10237.250
ARIMA(0, 2, 0) MSE=4461.104
ARIMA(0, 2, 1) MSE=3707.061
ARIMA(1, 0, 0) MSE=18617.077
ARIMA(1, 1, 0) MSE=4751.719
ARIMA(1, 2, 0) MSE=3438.192
ARIMA(3, 2, 0) MSE=4508.022
(1, 2, 0)
ARIMA(0, 0, 0) MSE=0.142
ARIMA(0, 1, 0) MSE=0.037
ARIMA(0, 2, 0) MSE=0.075
(0, 1, 0)
ARIMA(0, 0, 0) MSE=0.142
ARIMA(0, 1, 0) MSE=0.037
ARIMA(0, 2, 0) MSE=0.075
(0, 1, 0)
ARIMA(0, 0, 0) MSE=1.181
ARIMA(0, 1, 0) MSE=0.217
ARIMA(0, 2, 0) MSE=0.337
(0, 1, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=43.212
ARIMA(0, 1, 0) MSE=1.271
ARIMA(0, 2, 0) MSE=0.784
(0, 2, 0)
ARIMA(0, 0, 0) MSE=204.225
ARIMA(0, 1, 0) MSE=3.805
ARIMA(0, 2, 0) MSE=3.193
(0, 2, 0)
ARIMA(0, 0, 0) MSE=0.328
ARIMA(0, 1, 0) MSE=0.037
ARIMA(0, 2, 0) MSE=0.075
(0, 1, 0)
ARIMA(0, 0, 0) MSE=104073.954
ARIMA(0, 1, 0) MSE=2533.937
ARIMA(0, 2, 0) MSE=479.774
(0, 2, 0)
ARIMA(0, 0, 0) MSE=0.408
ARIMA(0, 1, 0) MSE=0.037
ARIMA(0, 2, 0) MSE=0.075
(0, 1, 0)
ARIMA(0, 0, 0) MSE=108.599
ARIMA(0, 0, 1) MSE=36.162
ARIMA(0, 1, 0) MSE=2.090
ARIMA(0, 1, 1) MSE=1.944
ARIMA(0, 1, 2) MSE=2.005
ARIMA(0, 2, 0) MSE=2.181
ARIMA(0, 2, 1) MSE=1.601
ARIMA(1, 0, 0) MSE=2.405
ARIMA(1, 1, 0) MSE=1.792
ARIMA(1, 2, 0) MSE=1.945
ARIMA(2, 0, 0) MSE=1.888
ARIMA(2, 1, 0) MSE=1.790
ARIMA(2, 2, 0) MSE=2.005
ARIMA(3, 0, 0) MSE=1.826
ARIMA(3, 1, 0) MSE=1.884
ARIMA(3, 2, 0) MSE=2.009
(0, 2, 1)
ARIMA(0, 0, 0) MSE=116.829
ARIMA(0, 1, 0) MSE=1.677
ARIMA(0, 2, 0) MSE=1.766
(0, 1, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=0.501
ARIMA(0, 1, 0) MSE=0.037
ARIMA(0, 2, 0) MSE=0.075
(0, 1, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=24.848
ARIMA(0, 1, 0) MSE=0.779
ARIMA(0, 2, 0) MSE=1.504
(0, 1, 0)
ARIMA(0, 0, 0) MSE=28638.854
ARIMA(0, 0, 1) MSE=8362.585
ARIMA(0, 1, 0) MSE=812.601
ARIMA(0, 1, 1) MSE=501.772
ARIMA(0, 1, 2) MSE=646.747
ARIMA(0, 2, 0) MSE=325.336
ARIMA(0, 2, 1) MSE=282.846
ARIMA(1, 0, 0) MSE=924.975
ARIMA(1, 1, 0) MSE=355.955
ARIMA(1, 2, 0) MSE=364.105
ARIMA(2, 1, 0) MSE=387.626
ARIMA(2, 2, 0) MSE=220.395
ARIMA(3, 1, 0) MSE=243.577
ARIMA(3, 2, 0) MSE=232.304
(2, 2, 0)
ARIMA(0, 0, 0) MSE=0.643
ARIMA(0, 1, 0) MSE=0.037
ARIMA(0, 2, 0) MSE=0.075
(0, 1, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=394.178
ARIMA(0, 1, 0) MSE=9.136
ARIMA(0, 2, 0) MSE=2.477
(0, 2, 0)
ARIMA(0, 0, 0) MSE=1741735.197
ARIMA(0, 0, 1) MSE=434341.399
ARIMA(0, 1, 0) MSE=2111.016
ARIMA(0, 1, 1) MSE=1522.556
ARIMA(0, 1, 2) MSE=756.199
ARIMA(0, 2, 0) MSE=19.698
ARIMA(0, 2, 1) MSE=13.468
ARIMA(1, 0, 0) MSE=77.154
ARIMA(1, 0, 1) MSE=53.444
ARIMA(1, 0, 2) MSE=39.920
ARIMA(1, 1, 0) MSE=865.755
ARIMA(1, 1, 1) MSE=58.312
ARIMA(1, 1, 2) MSE=38.250
ARIMA(1, 2, 0) MSE=13.283
ARIMA(1, 2, 1) MSE=11.746
ARIMA(1, 2, 2) MSE=12.040
ARIMA(2, 0, 0) MSE=20.961
ARIMA(2, 0, 2) MSE=110.034
ARIMA(2, 1, 0) MSE=127.464
ARIMA(2, 1, 1) MSE=39.170
ARIMA(2, 2, 0) MSE=11.993
ARIMA(2, 2, 1) MSE=11.751
ARIMA(3, 0, 0) MSE=26.173
ARIMA(3, 1, 0) MSE=68.383
ARIMA(3, 1, 1) MSE=39.100
ARIMA(3, 2, 0) MSE=11.735
ARIMA(3, 2, 1) MSE=12.783
(3, 2, 0)
ARIMA(0, 0, 0) MSE=536.008
ARIMA(0, 1, 0) MSE=17.341
ARIMA(0, 2, 0) MSE=11.642
(0, 2, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=4.685
ARIMA(0, 1, 0) MSE=0.476
ARIMA(0, 2, 0) MSE=0.976
(0, 1, 0)
ARIMA(0, 0, 0) MSE=2.537
ARIMA(0, 1, 0) MSE=0.109
ARIMA(0, 2, 0) MSE=0.226
(0, 1, 0)
ARIMA(0, 0, 0) MSE=63.992
ARIMA(0, 1, 0) MSE=1.460
ARIMA(0, 2, 0) MSE=1.240
(0, 2, 0)
ARIMA(0, 0, 0) MSE=27.027
ARIMA(0, 1, 0) MSE=0.906
ARIMA(0, 2, 0) MSE=0.860
(0, 2, 0)
ARIMA(0, 0, 0) MSE=0.597
ARIMA(0, 1, 0) MSE=0.037
ARIMA(0, 2, 0) MSE=0.075
(0, 1, 0)
ARIMA(0, 0, 0) MSE=32.167
ARIMA(0, 1, 0) MSE=0.779
ARIMA(0, 2, 0) MSE=1.240
(0, 1, 0)
ARIMA(0, 0, 0) MSE=1703.253
ARIMA(0, 1, 0) MSE=29.483
ARIMA(0, 2, 0) MSE=3.187
(0, 2, 0)
ARIMA(0, 0, 0) MSE=1.722
ARIMA(0, 1, 0) MSE=0.183
ARIMA(0, 2, 0) MSE=0.376
(0, 1, 0)
ARIMA(0, 0, 0) MSE=11952.690
ARIMA(0, 0, 1) MSE=3371.034
ARIMA(0, 1, 0) MSE=15.502
ARIMA(0, 1, 1) MSE=14.315
ARIMA(0, 1, 2) MSE=10.952
ARIMA(0, 2, 0) MSE=15.737
ARIMA(0, 2, 1) MSE=6.377
ARIMA(1, 0, 0) MSE=32.054
ARIMA(1, 1, 0) MSE=13.048
ARIMA(1, 1, 1) MSE=7.084
ARIMA(1, 1, 2) MSE=7.215
ARIMA(1, 2, 0) MSE=8.971
ARIMA(1, 2, 1) MSE=6.363
ARIMA(1, 2, 2) MSE=6.579
ARIMA(2, 0, 0) MSE=16.280
ARIMA(2, 1, 0) MSE=9.185
ARIMA(2, 2, 0) MSE=6.197
ARIMA(2, 2, 1) MSE=6.542
ARIMA(3, 0, 0) MSE=9.788
ARIMA(3, 1, 0) MSE=6.615
ARIMA(3, 2, 0) MSE=6.315
ARIMA(3, 2, 1) MSE=6.095
(3, 2, 1)
ARIMA(0, 0, 0) MSE=81.213
ARIMA(0, 1, 0) MSE=2.023
ARIMA(0, 2, 0) MSE=4.058
(0, 1, 0)
ARIMA(0, 0, 0) MSE=9711.887
ARIMA(0, 1, 0) MSE=98.079
ARIMA(0, 2, 0) MSE=22.646
(0, 2, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=2288.189
ARIMA(0, 1, 0) MSE=33.414
ARIMA(0, 2, 0) MSE=26.853
(0, 2, 0)
ARIMA(0, 0, 0) MSE=10469.332
ARIMA(0, 1, 0) MSE=218.422
ARIMA(0, 2, 0) MSE=155.068
(0, 2, 0)
ARIMA(0, 0, 0) MSE=2164.969
ARIMA(0, 0, 1) MSE=601.969
ARIMA(0, 1, 0) MSE=24.395
ARIMA(0, 1, 1) MSE=12.755
ARIMA(0, 2, 0) MSE=4.929
ARIMA(0, 2, 1) MSE=5.940
ARIMA(1, 0, 0) MSE=30.831
ARIMA(1, 1, 0) MSE=5.925
ARIMA(1, 2, 0) MSE=5.168
ARIMA(2, 1, 0) MSE=6.173
ARIMA(2, 2, 0) MSE=5.457
ARIMA(3, 1, 0) MSE=6.296
ARIMA(3, 2, 0) MSE=5.575
(0, 2, 0)
ARIMA(0, 0, 0) MSE=4.084
ARIMA(0, 1, 0) MSE=0.208
ARIMA(0, 2, 0) MSE=0.338
(0, 1, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=88.566
ARIMA(0, 1, 0) MSE=2.652
ARIMA(0, 2, 0) MSE=3.005
(0, 1, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=0.703
ARIMA(0, 1, 0) MSE=0.148
ARIMA(0, 2, 0) MSE=0.300
(0, 1, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=268.394
ARIMA(0, 1, 0) MSE=5.535
ARIMA(0, 2, 0) MSE=5.556
(0, 1, 0)
ARIMA(0, 0, 0) MSE=22400250.831
ARIMA(0, 0, 1) MSE=6364533.943
ARIMA(0, 1, 0) MSE=312364.087
ARIMA(0, 1, 1) MSE=180949.281
ARIMA(0, 2, 0) MSE=89051.768
ARIMA(0, 2, 1) MSE=91164.131
ARIMA(1, 0, 0) MSE=384102.221
ARIMA(1, 1, 0) MSE=93438.930
ARIMA(1, 2, 0) MSE=87120.943
ARIMA(2, 1, 0) MSE=101290.103
(1, 2, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=0.580
ARIMA(0, 1, 0) MSE=0.037
ARIMA(0, 2, 0) MSE=0.075
(0, 1, 0)
ARIMA(0, 0, 0) MSE=0.522
ARIMA(0, 1, 0) MSE=0.037
ARIMA(0, 2, 0) MSE=0.075
(0, 1, 0)
ARIMA(0, 0, 0) MSE=1.258
ARIMA(0, 1, 0) MSE=0.108
ARIMA(0, 2, 0) MSE=0.150
(0, 1, 0)
ARIMA(0, 0, 0) MSE=944499.229
ARIMA(0, 0, 1) MSE=260196.335
ARIMA(0, 1, 0) MSE=14228.749
ARIMA(0, 1, 1) MSE=6266.751
ARIMA(0, 2, 0) MSE=1274.236
ARIMA(0, 2, 1) MSE=1176.314
ARIMA(0, 2, 2) MSE=1147.491
ARIMA(1, 0, 0) MSE=17443.138
ARIMA(1, 1, 0) MSE=1295.948
ARIMA(1, 2, 0) MSE=1065.969
ARIMA(2, 2, 0) MSE=903.297
(2, 2, 0)
ARIMA(0, 0, 0) MSE=11.778
ARIMA(0, 1, 0) MSE=0.284
ARIMA(0, 2, 0) MSE=0.602
(0, 1, 0)
ARIMA(0, 0, 0) MSE=1664.795
ARIMA(0, 0, 1) MSE=456.358
ARIMA(0, 1, 0) MSE=12.517
ARIMA(0, 1, 1) MSE=9.271
ARIMA(0, 1, 2) MSE=9.812
ARIMA(0, 2, 0) MSE=8.568
ARIMA(0, 2, 1) MSE=5.388
ARIMA(1, 0, 0) MSE=16.157
ARIMA(1, 1, 0) MSE=7.678
ARIMA(1, 2, 0) MSE=7.452
ARIMA(2, 0, 0) MSE=8.171
ARIMA(2, 1, 0) MSE=7.648
(0, 2, 1)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=15.610
ARIMA(0, 1, 0) MSE=0.420
ARIMA(0, 2, 0) MSE=0.752
(0, 1, 0)
ARIMA(0, 0, 0) MSE=1.784
ARIMA(0, 1, 0) MSE=0.108
ARIMA(0, 2, 0) MSE=0.226
(0, 1, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=5.876
ARIMA(0, 0, 1) MSE=2.282
ARIMA(0, 1, 0) MSE=0.246
ARIMA(0, 1, 1) MSE=0.248
ARIMA(0, 1, 2) MSE=0.317
ARIMA(0, 2, 0) MSE=0.451
ARIMA(0, 2, 1) MSE=0.255
ARIMA(1, 0, 0) MSE=0.271
ARIMA(1, 1, 0) MSE=0.250
ARIMA(1, 2, 0) MSE=0.374
ARIMA(2, 0, 0) MSE=0.277
ARIMA(2, 1, 0) MSE=0.364
ARIMA(3, 1, 0) MSE=0.364
ARIMA(3, 2, 0) MSE=0.465
(0, 1, 0)
ARIMA(0, 0, 0) MSE=0.283
ARIMA(0, 1, 0) MSE=0.073
ARIMA(0, 2, 0) MSE=0.112
(0, 1, 0)
ARIMA(0, 0, 0) MSE=108.388
ARIMA(0, 1, 0) MSE=3.389
ARIMA(0, 2, 0) MSE=5.446
(0, 1, 0)
ARIMA(0, 0, 0) MSE=512.187
ARIMA(0, 1, 0) MSE=12.544
ARIMA(0, 2, 0) MSE=4.026
(0, 2, 0)
ARIMA(0, 0, 0) MSE=8.066
ARIMA(0, 1, 0) MSE=2.321
ARIMA(0, 2, 0) MSE=7.018
(0, 1, 0)
ARIMA(0, 0, 0) MSE=5179.716
ARIMA(0, 0, 1) MSE=1558.197
ARIMA(0, 1, 0) MSE=196.581
ARIMA(0, 1, 1) MSE=153.502
ARIMA(0, 1, 2) MSE=150.982
ARIMA(0, 2, 0) MSE=101.662
ARIMA(0, 2, 1) MSE=83.246
ARIMA(1, 0, 0) MSE=219.619
ARIMA(1, 1, 0) MSE=120.162
ARIMA(1, 1, 1) MSE=95.119
ARIMA(1, 2, 0) MSE=94.432
ARIMA(2, 1, 0) MSE=113.328
(0, 2, 1)
ARIMA(0, 0, 0) MSE=14034.108
ARIMA(0, 0, 1) MSE=4374.570
ARIMA(0, 1, 0) MSE=138.072
ARIMA(0, 1, 1) MSE=98.933
ARIMA(0, 1, 2) MSE=87.601
ARIMA(0, 2, 0) MSE=57.106
ARIMA(0, 2, 1) MSE=53.009
ARIMA(1, 0, 0) MSE=175.163
ARIMA(1, 1, 0) MSE=62.878
ARIMA(1, 2, 0) MSE=53.192
ARIMA(2, 0, 0) MSE=64.567
ARIMA(2, 1, 0) MSE=58.552
ARIMA(2, 2, 0) MSE=54.596
(0, 2, 1)
ARIMA(0, 0, 0) MSE=4690596.447
ARIMA(0, 0, 1) MSE=1212580.147
ARIMA(0, 1, 0) MSE=10273.836
ARIMA(0, 1, 1) MSE=3140.840
ARIMA(0, 2, 0) MSE=171.984
ARIMA(0, 2, 1) MSE=170.134
ARIMA(0, 2, 2) MSE=185.548
ARIMA(1, 0, 0) MSE=18170.928
ARIMA(1, 1, 0) MSE=171.090
ARIMA(1, 2, 0) MSE=174.074
ARIMA(2, 1, 0) MSE=185.963
ARIMA(2, 2, 0) MSE=186.959
ARIMA(3, 2, 0) MSE=191.002
(0, 2, 1)
ARIMA(0, 0, 0) MSE=1281.049
ARIMA(0, 0, 1) MSE=382.225
ARIMA(0, 1, 0) MSE=6.114
ARIMA(0, 1, 1) MSE=5.194
ARIMA(0, 1, 2) MSE=5.337
ARIMA(0, 2, 0) MSE=5.755
ARIMA(0, 2, 1) MSE=3.632
ARIMA(1, 0, 0) MSE=8.272
ARIMA(1, 1, 0) MSE=4.711
ARIMA(1, 2, 0) MSE=4.845
ARIMA(1, 2, 1) MSE=4.033
ARIMA(2, 0, 0) MSE=5.057
ARIMA(2, 1, 0) MSE=4.579
ARIMA(2, 2, 0) MSE=5.068
ARIMA(2, 2, 1) MSE=4.675
ARIMA(3, 1, 0) MSE=4.960
ARIMA(3, 2, 0) MSE=4.414
(0, 2, 1)
ARIMA(0, 0, 0) MSE=9241.662
ARIMA(0, 0, 1) MSE=2731.000
ARIMA(0, 1, 0) MSE=166.079
ARIMA(0, 1, 1) MSE=107.465
ARIMA(0, 1, 2) MSE=76.409
ARIMA(0, 2, 0) MSE=38.311
ARIMA(0, 2, 1) MSE=30.188
ARIMA(1, 0, 0) MSE=199.063
ARIMA(1, 1, 0) MSE=42.591
ARIMA(1, 2, 0) MSE=27.313
ARIMA(2, 1, 0) MSE=29.486
ARIMA(2, 2, 0) MSE=30.726
(1, 2, 0)
ARIMA(0, 0, 0) MSE=948.215
ARIMA(0, 1, 0) MSE=19.493
ARIMA(0, 2, 0) MSE=5.065
(0, 2, 0)
ARIMA(0, 0, 0) MSE=87741904.663
ARIMA(0, 0, 1) MSE=22786321.375
ARIMA(0, 1, 0) MSE=275695.289
ARIMA(0, 1, 1) MSE=104492.032
ARIMA(0, 2, 0) MSE=14021.329
ARIMA(0, 2, 1) MSE=12113.845
ARIMA(1, 0, 0) MSE=438245.509
ARIMA(1, 1, 0) MSE=16673.708
ARIMA(1, 2, 0) MSE=13756.679
ARIMA(2, 1, 0) MSE=14231.065
ARIMA(2, 2, 0) MSE=20921.744
(0, 2, 1)
ARIMA(0, 0, 0) MSE=3.217
ARIMA(0, 1, 0) MSE=0.218
ARIMA(0, 2, 0) MSE=0.451
(0, 1, 0)
ARIMA(0, 0, 0) MSE=2104.910
ARIMA(0, 0, 1) MSE=556.184
ARIMA(0, 1, 0) MSE=13.409
ARIMA(0, 1, 1) MSE=13.472
ARIMA(0, 1, 2) MSE=12.261
ARIMA(0, 2, 0) MSE=23.231
ARIMA(0, 2, 1) MSE=10.072
ARIMA(1, 0, 0) MSE=17.371
ARIMA(1, 1, 0) MSE=13.699
ARIMA(1, 1, 2) MSE=11.831
ARIMA(1, 2, 0) MSE=12.889
ARIMA(1, 2, 1) MSE=11.117
ARIMA(1, 2, 2) MSE=11.419
ARIMA(2, 0, 0) MSE=16.203
ARIMA(2, 1, 0) MSE=11.713
ARIMA(2, 1, 2) MSE=11.950
ARIMA(2, 2, 0) MSE=12.045
ARIMA(3, 0, 0) MSE=12.879
ARIMA(3, 1, 0) MSE=11.728
ARIMA(3, 2, 0) MSE=12.894
(0, 2, 1)
ARIMA(0, 0, 0) MSE=10.870
ARIMA(0, 1, 0) MSE=0.390
ARIMA(0, 2, 0) MSE=0.488
(0, 1, 0)
ARIMA(0, 0, 0) MSE=10.226
ARIMA(0, 1, 0) MSE=1.248
ARIMA(0, 2, 0) MSE=3.349
(0, 1, 0)
ARIMA(0, 0, 0) MSE=7.245
ARIMA(0, 1, 0) MSE=0.390
ARIMA(0, 2, 0) MSE=0.638
(0, 1, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=0.208
ARIMA(0, 1, 0) MSE=0.037
ARIMA(0, 2, 0) MSE=0.075
(0, 1, 0)
ARIMA(0, 0, 0) MSE=2.343
ARIMA(0, 1, 0) MSE=0.368
ARIMA(0, 2, 0) MSE=0.751
(0, 1, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=0.730
ARIMA(0, 1, 0) MSE=0.108
ARIMA(0, 2, 0) MSE=0.187
(0, 1, 0)
ARIMA(0, 0, 0) MSE=97.511
ARIMA(0, 0, 1) MSE=30.891
ARIMA(0, 1, 0) MSE=0.810
ARIMA(0, 1, 1) MSE=0.805
ARIMA(0, 1, 2) MSE=0.786
ARIMA(0, 2, 0) MSE=1.053
ARIMA(0, 2, 1) MSE=0.618
ARIMA(0, 2, 2) MSE=0.677
ARIMA(1, 0, 0) MSE=0.998
ARIMA(1, 1, 0) MSE=0.741
ARIMA(1, 2, 0) MSE=0.674
ARIMA(2, 0, 0) MSE=0.829
ARIMA(2, 1, 0) MSE=0.709
ARIMA(2, 2, 0) MSE=0.878
ARIMA(3, 0, 0) MSE=0.743
(0, 2, 1)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=2.097
ARIMA(0, 1, 0) MSE=0.218
ARIMA(0, 2, 0) MSE=0.300
(0, 1, 0)
ARIMA(0, 0, 0) MSE=0.270
ARIMA(0, 1, 0) MSE=0.037
ARIMA(0, 2, 0) MSE=0.075
(0, 1, 0)
ARIMA(0, 0, 0) MSE=0.208
ARIMA(0, 1, 0) MSE=0.037
ARIMA(0, 2, 0) MSE=0.075
(0, 1, 0)
ARIMA(0, 0, 0) MSE=52.784
ARIMA(0, 1, 0) MSE=0.854
ARIMA(0, 2, 0) MSE=1.015
(0, 1, 0)
ARIMA(0, 0, 0) MSE=474.913
ARIMA(0, 1, 0) MSE=6.814
ARIMA(0, 2, 0) MSE=6.600
(0, 2, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=0.108
ARIMA(0, 1, 0) MSE=0.037
ARIMA(0, 2, 0) MSE=0.075
(0, 1, 0)
ARIMA(0, 0, 0) MSE=1139.826
ARIMA(0, 1, 0) MSE=8.403
ARIMA(0, 2, 0) MSE=7.220
(0, 2, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=7.176
ARIMA(0, 1, 0) MSE=0.389
ARIMA(0, 2, 0) MSE=0.751
(0, 1, 0)
ARIMA(0, 0, 0) MSE=0.183
ARIMA(0, 1, 0) MSE=0.073
ARIMA(0, 2, 0) MSE=0.037
(0, 2, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=0.356
ARIMA(0, 1, 0) MSE=0.037
ARIMA(0, 2, 0) MSE=0.075
(0, 1, 0)
ARIMA(0, 0, 0) MSE=15.093
ARIMA(0, 1, 0) MSE=0.315
ARIMA(0, 2, 0) MSE=0.376
(0, 1, 0)
ARIMA(0, 0, 0) MSE=1.026
ARIMA(0, 1, 0) MSE=0.073
ARIMA(0, 2, 0) MSE=0.150
(0, 1, 0)
ARIMA(0, 0, 0) MSE=3029.240
ARIMA(0, 1, 0) MSE=111.093
ARIMA(0, 2, 0) MSE=37.948
(0, 2, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=0.382
ARIMA(0, 1, 0) MSE=0.037
ARIMA(0, 2, 0) MSE=0.075
(0, 1, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=1.430
ARIMA(0, 1, 0) MSE=0.073
ARIMA(0, 2, 0) MSE=0.150
(0, 1, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=1607.075
ARIMA(0, 0, 1) MSE=439.363
ARIMA(0, 1, 0) MSE=23.795
ARIMA(0, 1, 1) MSE=13.882
ARIMA(0, 1, 2) MSE=14.106
ARIMA(0, 2, 0) MSE=12.398
ARIMA(0, 2, 1) MSE=15.435
ARIMA(1, 0, 0) MSE=28.126
ARIMA(1, 1, 0) MSE=13.495
ARIMA(1, 2, 0) MSE=20.637
ARIMA(2, 1, 0) MSE=20.390
ARIMA(2, 2, 0) MSE=18.419
ARIMA(3, 2, 0) MSE=21.675
(0, 2, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=1037315.722
ARIMA(0, 0, 1) MSE=280315.836
ARIMA(0, 1, 0) MSE=9159.170
ARIMA(0, 1, 1) MSE=5028.512
ARIMA(0, 2, 0) MSE=1632.125
ARIMA(0, 2, 1) MSE=1124.343
ARIMA(1, 0, 0) MSE=11893.010
ARIMA(1, 1, 0) MSE=1637.186
ARIMA(1, 2, 0) MSE=1212.749
ARIMA(2, 1, 0) MSE=1232.883
(0, 2, 1)
ARIMA(0, 0, 0) MSE=0.000
ARIMA(0, 1, 0) MSE=0.000
ARIMA(0, 2, 0) MSE=0.000
(0, 0, 0)
ARIMA(0, 0, 0) MSE=0.382
ARIMA(0, 1, 0) MSE=0.037
ARIMA(0, 2, 0) MSE=0.075
(0, 1, 0)
ARIMA(0, 0, 0) MSE=0.433
ARIMA(0, 1, 0) MSE=0.037
ARIMA(0, 2, 0) MSE=0.075
(0, 1, 0)
ARIMA(0, 0, 0) MSE=23.615
ARIMA(0, 1, 0) MSE=0.806
ARIMA(0, 2, 0) MSE=1.277
(0, 1, 0)
ARIMA(0, 0, 0) MSE=7.198
ARIMA(0, 1, 0) MSE=0.314
ARIMA(0, 2, 0) MSE=0.638
(0, 1, 0)
ARIMA(0, 0, 0) MSE=133.869
ARIMA(0, 1, 0) MSE=2.871
ARIMA(0, 2, 0) MSE=2.591
(0, 2, 0)
ARIMA(0, 0, 0) MSE=1772.059
ARIMA(0, 1, 0) MSE=24.354
ARIMA(0, 2, 0) MSE=10.988
(0, 2, 0)
ARIMA(0, 0, 0) MSE=1.101
ARIMA(0, 1, 0) MSE=0.108
ARIMA(0, 2, 0) MSE=0.187
(0, 1, 0)
ARIMA(0, 0, 0) MSE=727.320
ARIMA(0, 1, 0) MSE=9.348
ARIMA(0, 2, 0) MSE=5.629
(0, 2, 0)

In [45]:
len(predictions)

12331

In [0]:
predic=[]
for i in predictions :
  predic.append(i//1)

In [0]:
sub=pd.read_csv('/content/testcorona.csv')

In [48]:
len(sub)

19646

In [49]:
sub.tail()

        Territory X Date  target
19641  Zimbabwe X 6/3/20     0.0
19642  Zimbabwe X 6/4/20     0.0
19643  Zimbabwe X 6/5/20     0.0
19644  Zimbabwe X 6/6/20     0.0
19645  Zimbabwe X 6/7/20     0.0

In [0]:
test=sub

In [0]:
test['Region']=0
test['Date']=0

for i in range (len(test)):
     
     test['Region'][i]=(str(test['Territory X Date'][i]).split(' X '))[0]
     test['Date'][i]=(str(test['Territory X Date'][i]).split(' X '))[1]

In [52]:
test.head()

        Territory X Date  target       Region     Date
0   Afghanistan X 3/6/20     0.0  Afghanistan   3/6/20
1   Afghanistan X 3/7/20     0.0  Afghanistan   3/7/20
2   Afghanistan X 3/8/20     0.0  Afghanistan   3/8/20
3   Afghanistan X 3/9/20     0.0  Afghanistan   3/9/20
4  Afghanistan X 3/10/20     0.0  Afghanistan  3/10/20

In [0]:
test['Date']=pd.to_datetime(test['Date'])
test.index=test['Date']

In [54]:
test.head()

                 Territory X Date  target       Region       Date
Date
2020-03-06   Afghanistan X 3/6/20     0.0  Afghanistan 2020-03-06
2020-03-07   Afghanistan X 3/7/20     0.0  Afghanistan 2020-03-07
2020-03-08   Afghanistan X 3/8/20     0.0  Afghanistan 2020-03-08
2020-03-09   Afghanistan X 3/9/20     0.0  Afghanistan 2020-03-09
2020-03-10  Afghanistan X 3/10/20     0.0  Afghanistan 2020-03-10

In [55]:
len(test['2020-04-10':]),len(predictions)

(12331, 12331)

In [0]:
test['2020-04-10':]['target']=predictions

In [58]:
predictions

[15.192307692307692,
 15.384615384615383,
 15.576923076923075,
 15.769230769230766,
 15.961538461538458,
 16.15384615384615,
 16.346153846153843,
 16.538461538461537,
 16.73076923076923,
 16.923076923076923,
 17.115384615384617,
 17.30769230769231,
 17.500000000000004,
 17.692307692307697,
 17.88461538461539,
 18.076923076923084,
 18.269230769230777,
 18.46153846153847,
 18.653846153846164,
 18.846153846153857,
 19.03846153846155,
 19.230769230769244,
 19.423076923076938,
 19.61538461538463,
 19.807692307692324,
 20.000000000000018,
 20.19230769230771,
 20.384615384615405,
 20.576923076923098,
 20.76923076923079,
 20.961538461538485,
 21.153846153846178,
 21.34615384615387,
 21.538461538461565,
 21.73076923076926,
 21.92307692307695,
 22.115384615384645,
 22.30769230769234,
 22.500000000000032,
 22.692307692307725,
 22.88461538461542,
 23.076923076923112,
 23.269230769230806,
 23.4615384615385,
 23.653846153846192,
 23.846153846153886,
 24.03846153846158,
 24.230769230769273,
 24.423076923076966,
 24.61538461538466,
 24.807692307692353,
 25.000000000000046,
 25.19230769230774,
 25.384615384615433,
 25.576923076923126,
 25.76923076923082,
 25.961538461538513,
 26.153846153846207,
 26.3461538461539,
 23.940437005243417,
 24.626176522512427,
 25.089099023093247,
 26.07726079083413,
 26.91760001446898,
 27.585892074735057,
 28.298338891892694,
 29.241111907828063,
 30.042143565035392,
 30.78353420588712,
 31.61753364452719,
 32.52657879061018,
 33.342340983735795,
 34.1642849796783,
 35.056205802953116,
 35.958209972375386,
 36.815825981884075,
 37.70264276546325,
 38.628312672711374,
 39.54662444375075,
 40.45358023457298,
 41.390056382803245,
 42.344711888842305,
 43.29382026725546,
 44.248498480184956,
 45.225699926544486,
 46.211609740734396,
 47.19832652355996,
 48.19684937511312,
 49.21116148562384,
 50.23165656023255,
 51.25813333899142,
 52.297331619024334,
 53.348090002397655,
 54.40552167983407,
 55.47179403130032,
 56.54985552736987,
 57.63752093007824,
 58.73306393748763,
 59.83855359210962,
 60.95472422166578,
 62.07992009433818,
 63.21396440240917,
 64.35813505114601,
 65.51224476011754,
 66.67541245297929,
 67.84797302909155,
 69.03050189757757,
 70.22261204328929,
 71.42397677694352,
 72.6349534594376,
 73.85570048937139,
 75.0859162410736,
 76.32555705458154,
 77.57485329851681,
 78.8337837926898,
 80.1021837045673,
 81.38010793756027,
 82.66766409164353,
 265.38961038961037,
 296.16883116883116,
 327.3376623376623,
 358.8961038961039,
 390.84415584415586,
 423.1818181818182,
 455.90909090909093,
 489.02597402597405,
 522.5324675324675,
 556.4285714285714,
 590.7142857142858,
 625.3896103896104,
 660.4545454545455,
 695.909090909091,
 731.7532467532468,
 767.987012987013,
 804.6103896103897,
 841.6233766233767,
 879.025974025974,
 916.8181818181819,
 955.0,
 993.5714285714286,
 1032.5324675324675,
 1071.8831168831168,
 1111.6233766233765,
 1151.7532467532467,
 1192.2727272727273,
 1233.1818181818182,
 1274.4805194805194,
 1316.168831168831,
 1358.246753246753,
 1400.7142857142856,
 1443.5714285714284,
 1486.8181818181818,
 1530.4545454545455,
 1574.4805194805194,
 1618.8961038961038,
 1663.7012987012986,
 1708.8961038961038,
 1754.4805194805194,
 1800.4545454545455,
 1846.8181818181818,
 1893.5714285714284,
 1940.7142857142856,
 1988.246753246753,
 2036.168831168831,
 2084.4805194805194,
 2133.181818181818,
 2182.272727272727,
 2231.7532467532465,
 2281.6233766233763,
 2331.8831168831166,
 2382.5324675324673,
 2433.5714285714284,
 2485.0,
 2536.818181818182,
 2589.0259740259744,
 2641.6233766233768,
 2694.6103896103896,
 27.025974025974026,
 29.07792207792208,
 31.155844155844157,
 33.25974025974026,
 35.38961038961039,
 37.54545454545455,
 39.72727272727273,
 41.93506493506493,
 44.16883116883116,
 46.428571428571416,
 48.7142857142857,
 51.02597402597401,
 53.363636363636346,
 55.727272727272705,
 58.116883116883095,
 60.53246753246751,
 62.97402597402594,
 65.4415584415584,
 67.93506493506489,
 70.4545454545454,
 72.99999999999994,
 75.57142857142851,
 78.1688311688311,
 80.79220779220772,
 83.44155844155836,
 86.11688311688303,
 88.81818181818173,
 91.54545454545445,
 94.29870129870119,
 97.07792207792197,
 99.88311688311677,
 102.7142857142856,
 105.57142857142844,
 108.45454545454531,
 111.36363636363622,
 114.29870129870115,
 117.2597402597401,
 120.24675324675307,
 123.25974025974008,
 126.29870129870112,
 129.36363636363618,
 132.45454545454527,
 135.57142857142838,
 138.71428571428552,
 141.88311688311668,
 145.07792207792187,
 148.29870129870108,
 151.5454545454543,
 154.81818181818156,
 158.11688311688283,
 161.44155844155816,
 164.7922077922075,
 168.16883116883088,
 171.57142857142827,
 174.9999999999997,
 178.45454545454513,
 181.9350649350646,
 185.44155844155807,
 188.97402597402558,
 2.0256410234666187,
 2.0512820469332373,
 2.076923070399856,
 2.1025640938664747,
 2.1282051173330934,
 2.153846140799712,
 2.1794871642663307,
 2.2051281877329494,
 2.230769211199568,
 2.2564102346661867,
 2.2820512581328054,
 2.307692281599424,
 2.3333333050660428,
 2.3589743285326614,
 2.38461535199928,
 2.4102563754658988,
 2.4358973989325174,
 2.461538422399136,
 2.487179445865755,
 2.5128204693323735,
 2.538461492798992,
 2.564102516265611,
 2.5897435397322295,
 2.615384563198848,
 2.641025586665467,
 2.6666666101320855,
 2.692307633598704,
 2.717948657065323,
 2.7435896805319415,
 2.76923070399856,
 2.794871727465179,
 2.8205127509317975,
 2.846153774398416,
 2.871794797865035,
 2.8974358213316536,
 2.9230768447982722,
 2.948717868264891,
 2.9743588917315096,
 2.9999999151981283,
 3.025640938664747,
 3.0512819621313656,
 3.0769229855979843,
 3.102564009064603,
 3.1282050325312216,
 3.1538460559978403,
 3.179487079464459,
 3.2051281029310776,
 3.2307691263976963,
 3.256410149864315,
 3.2820511733309337,
 3.3076921967975523,
 3.333333220264171,
 3.3589742437307897,
 3.3846152671974084,
 3.410256290664027,
 3.4358973141306457,
 3.4615383375972644,
 3.487179361063883,
 3.5128203845305017,
 2.0256410256409594,
 2.0512820512819188,
 2.076923076922878,
 2.1025641025638375,
 2.128205128204797,
 2.1538461538457563,
 2.1794871794867157,
 2.205128205127675,
 2.2307692307686344,
 2.256410256409594,
 2.282051282050553,
 2.3076923076915126,
 2.333333333332472,
 2.3589743589734313,
 2.3846153846143907,
 2.41025641025535,
 2.4358974358963095,
 2.461538461537269,
 2.4871794871782282,
 2.5128205128191876,
 2.538461538460147,
 2.5641025641011064,
 2.5897435897420658,
 2.615384615383025,
 2.6410256410239845,
 2.666666666664944,
 2.6923076923059033,
 2.7179487179468627,
 2.743589743587822,
 2.7692307692287814,
 2.794871794869741,
 2.8205128205107,
 2.8461538461516596,
 2.871794871792619,
 2.8974358974335783,
 2.9230769230745377,
 2.948717948715497,
 2.9743589743564565,
 2.999999999997416,
 3.0256410256383752,
 3.0512820512793346,
 3.076923076920294,
 3.1025641025612534,
 3.1282051282022127,
 3.153846153843172,
 3.1794871794841315,
 3.205128205125091,
 3.2307692307660503,
 3.2564102564070097,
 3.282051282047969,
 3.3076923076889284,
 3.333333333329888,
 3.358974358970847,
 3.3846153846118066,
 3.410256410252766,
 3.4358974358937253,
 3.4615384615346847,
 3.487179487175644,
 3.5128205128166035,
 79.06463849195617,
 86.22211350953421,
 93.47242505273412,
 100.8155731215559,
 108.25155771599955,
 115.78037883606507,
 123.40203648175246,
 131.11653065306172,
 138.92386134999285,
 146.82402857254584,
 154.8170323207207,
 162.90287259451742,
 171.08154939393603,
 179.3530627189765,
 187.71741256963884,
 196.17459894592304,
 204.72462184782913,
 213.36748127535708,
 222.1031772285069,
 230.93170970727857,
 239.85307871167214,
 248.86728424168757,
 257.97432629732486,
 267.174204878584,
 276.46691998546504,
 285.8524716179679,
 295.3308597760927,
 304.9020844598394,
 314.5661456692079,
 324.3230434041983,
 334.17277766481055,
 344.11534845104467,
 354.15075576290064,
 364.2789996003785,
 374.50007996347824,
 384.81399685219986,
 395.22075026654335,
 405.7203402065087,
 416.3127666720959,
 426.998029663305,
 437.7761291801359,
 448.6470652225887,
 459.6108377906634,
 470.66744688436,
 481.81689250367845,
 493.05917464861875,
 504.3942933191809,
 515.822248515365,
 527.343040237171,
 538.9566684845987,
 550.6631332576484,
 562.4624345563199,
 574.3545723806133,
 586.3395467305285,
 598.4173576060656,
 610.5880050072246,
 622.8514889340055,
 635.2078093864083,
 647.6569663644328,
 10.128205128126497,
 10.256410256252995,
 10.384615384379492,
 10.51282051250599,
 10.641025640632487,
 10.769230768758984,
 10.897435896885481,
 11.025641025011979,
 11.153846153138476,
 11.282051281264973,
 11.41025640939147,
 11.538461537517968,
 11.666666665644465,
 11.794871793770962,
 11.92307692189746,
 12.051282050023957,
 12.179487178150454,
 12.307692306276952,
 12.435897434403449,
 12.564102562529946,
 12.692307690656444,
 12.820512818782941,
 12.948717946909438,
 13.076923075035936,
 13.205128203162433,
 13.33333333128893,
 13.461538459415427,
 13.589743587541925,
 13.717948715668422,
 13.84615384379492,
 13.974358971921417,
 14.102564100047914,
 14.230769228174411,
 14.358974356300909,
 14.487179484427406,
 14.615384612553903,
 14.7435897406804,
 14.871794868806898,
 14.999999996933395,
 15.128205125059893,
 15.25641025318639,
 15.384615381312887,
 15.512820509439385,
 15.641025637565882,
 15.76923076569238,
 15.897435893818876,
 16.025641021945372,
 16.153846150071868,
 16.282051278198363,
 16.41025640632486,
 16.538461534451354,
 16.66666666257785,
 16.794871790704345,
 16.92307691883084,
 17.051282046957336,
 17.179487175083832,
 17.307692303210327,
 17.435897431336823,
 17.56410255946332,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 54.567712095628075,
 58.18281455446507,
 61.84530737651098,
 65.55519056176581,
 69.31246411022957,
 73.11712802190225,
 76.96918229678384,
 80.86862693487436,
 84.81546193617379,
 88.80968730068214,
 92.85130302839941,
 96.9403091193256,
 101.07670557346071,
 105.26049239080474,
 109.4916695713577,
 113.77023711511958,
 118.09619502209038,
 122.4695432922701,
 126.89028192565874,
 131.3584109222563,
 135.87393028206276,
 140.43684000507815,
 145.04714009130248,
 149.7048305407357,
 154.40991135337788,
 159.16238252922895,
 163.96224406828895,
 168.80949597055786,
 173.7041382360357,
 178.64617086472245,
 183.63559385661813,
 188.6724072117227,
 193.75661093003623,
 198.88820501155865,
 204.06718945629,
 209.29356426423027,
 214.56732943537946,
 219.88848496973756,
 225.2570308673046,
 230.67296712808056,
 236.13629375206543,
 241.64701073925923,
 247.20511808966194,
 252.81061580327358,
 258.46350388009415,
 264.16378232012363,
 269.91145112336204,
 275.70651028980933,
 281.54895981946555,
 287.4387997123307,
 293.3760299684048,
 299.36065058768776,
 305.39266157017965,
 311.4720629158805,
 317.59885462479025,
 323.77303669690895,
 329.9946091322365,
 336.263571930773,
 342.57992509251847,
 319.02142344042636,
 343.3549165133421,
 368.0004792187472,
 392.95811155664165,
 418.2278135270255,
 443.80958512989866,
 469.7034263652612,
 495.9093372331131,
 522.4273177334544,
 549.257367866285,
 576.399487631605,
 603.8536770294144,
 631.619936059713,
 659.6982647225011,
 688.0886630177786,
 716.7911309455453,
 745.8056685058015,
 775.132275698547,
 804.7709525237818,
 834.721698981506,
 864.9845150717197,
 895.5594007944226,
 926.4463561496149,
 957.6453811372966,
 989.1564757574677,
 1020.979640010128,
 1053.1148738952777,
 1085.5621774129168,
 1118.3215505630453,
 1151.3929933456632,
 1184.7765057607703,
 1218.472087808367,
 1252.4797394884529,
 1286.799460801028,
 1321.4312517460928,
 1356.3751123236468,
 1391.63104253369,
 1427.199042376223,
 1463.079111851245,
 1499.2712509587564,
 1535.7754596987572,
 1572.5917380712474,
 1609.7200860762268,
 1647.1605037136958,
 1684.912990983654,
 1722.9775478861015,
 1761.3541744210386,
 1800.042870588465,
 1839.0436363883807,
 1878.3564718207858,
 1917.9813768856802,
 1957.9183515830641,
 1998.1673959129373,
 2038.7285098752998,
 2079.6016934701515,
 2120.7869466974926,
 2162.284269557323,
 2204.093662049643,
 2246.2151241744523,
 9.455179456552546,
 9.917307972475031,
 10.386385547767457,
 10.862412182429821,
 11.345387876462127,
 11.83531262986437,
 12.332186442636553,
 12.836009314778677,
 13.346781246290739,
 13.864502237172742,
 14.389172287424683,
 14.920791397046566,
 15.459359566038387,
 16.004876794400147,
 16.557343082131847,
 17.11675842923349,
 17.683122835705067,
 18.256436301546586,
 18.836698826758045,
 19.423910411339445,
 20.018071055290783,
 20.61918075861206,
 21.22723952130328,
 21.842247343364434,
 22.46420422479553,
 23.093110165596567,
 23.728965165767544,
 24.37176922530846,
 25.021522344219314,
 25.67822452250011,
 26.34187576015084,
 27.012476057171515,
 27.69002541356213,
 28.374523829322683,
 29.065971304453175,
 29.764367838953607,
 30.46971343282398,
 31.182008086064293,
 31.901251798674544,
 32.62744457065473,
 33.36058640200486,
 34.10067729272493,
 34.847717242814944,
 35.601706252274894,
 36.36264432110478,
 37.13053144930461,
 37.90536763687438,
 38.687152883814086,
 39.475887190123736,
 40.27157055580332,
 41.074202980852846,
 41.88378446527231,
 42.70031500906172,
 43.52379461222107,
 44.35422327475035,
 45.191600996649576,
 46.035927777918744,
 46.88720361855785,
 47.74542851856689,
 8.102564101717057,
 8.205128203434114,
 8.307692305151171,
 8.410256406868228,
 8.512820508585285,
 8.615384610302343,
 8.7179487120194,
 8.820512813736457,
 8.923076915453514,
 9.025641017170571,
 9.128205118887628,
 9.230769220604685,
 9.333333322321742,
 9.4358974240388,
 9.538461525755856,
 9.641025627472914,
 9.74358972918997,
 9.846153830907028,
 9.948717932624085,
 10.051282034341142,
 10.153846136058199,
 10.256410237775256,
 10.358974339492313,
 10.46153844120937,
 10.564102542926427,
 10.666666644643485,
 10.769230746360542,
 10.871794848077599,
 10.974358949794656,
 11.076923051511713,
 11.17948715322877,
 11.282051254945827,
 11.384615356662884,
 11.487179458379941,
 11.589743560096998,
 11.692307661814056,
 11.794871763531113,
 11.89743586524817,
 11.999999966965227,
 12.102564068682284,
 12.205128170399341,
 12.307692272116398,
 12.410256373833455,
 12.512820475550512,
 12.61538457726757,
 12.717948678984627,
 12.820512780701684,
 12.92307688241874,
 13.025640984135798,
 13.128205085852855,
 13.230769187569912,
 13.33333328928697,
 13.435897391004026,
 13.538461492721083,
 13.64102559443814,
 13.743589696155198,
 13.846153797872255,
 13.948717899589312,
 14.051282001306369,
 5.064102564096069,
 5.128205128192137,
 5.192307692288206,
 5.2564102563842745,
 5.320512820480343,
 5.384615384576412,
 5.44871794867248,
 5.512820512768549,
 5.576923076864618,
 5.641025640960686,
 5.705128205056755,
 5.7692307691528235,
 5.833333333248892,
 5.897435897344961,
 5.961538461441029,
 6.025641025537098,
 6.089743589633167,
 6.153846153729235,
 6.217948717825304,
 6.2820512819213725,
 6.346153846017441,
 6.41025641011351,
 6.474358974209578,
 6.538461538305647,
 6.602564102401716,
 6.666666666497784,
 6.730769230593853,
 6.7948717946899215,
 6.85897435878599,
 6.923076922882059,
 6.987179486978127,
 7.051282051074196,
 7.115384615170265,
 7.179487179266333,
 7.243589743362402,
 7.3076923074584705,
 7.371794871554539,
 7.435897435650608,
 7.499999999746676,
 7.564102563842745,
 7.628205127938814,
 7.692307692034882,
 7.756410256130951,
 7.8205128202270195,
 7.884615384323088,
 7.948717948419157,
 8.012820512515226,
 8.076923076611296,
 8.141025640707365,
 8.205128204803435,
 8.269230768899504,
 8.333333332995574,
 8.397435897091643,
 8.461538461187713,
 8.525641025283782,
 8.589743589379852,
 8.653846153475921,
 8.717948717571991,
 8.78205128166806,
 22.01298701298701,
 23.038961038961038,
 24.077922077922075,
 25.129870129870127,
 26.19480519480519,
 27.27272727272727,
 28.36363636363636,
 29.467532467532465,
 30.58441558441558,
 31.71428571428571,
 32.857142857142854,
 34.01298701298701,
 35.18181818181818,
 36.36363636363636,
 37.55844155844156,
 38.76623376623377,
 39.98701298701299,
 41.22077922077922,
 42.46753246753247,
 43.727272727272734,
 45.00000000000001,
 46.28571428571429,
 47.584415584415595,
 48.89610389610391,
 50.220779220779235,
 51.55844155844157,
 52.90909090909093,
 54.272727272727295,
 55.64935064935067,
 57.03896103896106,
 58.44155844155847,
 59.85714285714289,
 61.28571428571432,
 62.72727272727276,
 64.18181818181822,
 65.64935064935068,
 67.12987012987017,
 68.62337662337667,
 70.12987012987018,
 71.64935064935071,
 73.18181818181824,
 74.72727272727279,
 76.28571428571435,
 77.85714285714292,
 79.44155844155851,
 81.03896103896112,
 82.64935064935074,
 84.27272727272737,
 85.909090909091,
 87.55844155844166,
 89.22077922077932,
 90.896103896104,
 92.5844155844157,
 94.2857142857144,
 96.00000000000013,
 97.72727272727286,
 99.4675324675326,
 101.22077922077936,
 102.98701298701313,
 2.9999999980933962,
 2.9999999942801883,
 2.9999999885603765,
 2.9999999809339606,
 2.999999971400941,
 2.999999959961317,
 2.9999999466150893,
 2.9999999313622574,
 2.9999999142028217,
 2.9999998951367823,
 2.9999998741641387,
 2.9999998512848913,
 2.9999998264990397,
 2.9999997998065844,
 2.999999771207525,
 2.9999997407018615,
 2.999999708289594,
 2.9999996739707226,
 2.999999637745247,
 2.999999599613168,
 2.999999559574485,
 2.9999995176291976,
 2.9999994737773066,
 2.9999994280188114,
 2.9999993803537124,
 2.999999330782009,
 2.9999992793037022,
 2.999999225918791,
 2.999999170627276,
 2.9999991134291575,
 2.9999990543244346,
 2.999998993313108,
 2.999998930395177,
 2.9999988655706424,
 2.9999987988395036,
 2.999998730201761,
 2.999998659657414,
 2.9999985872064636,
 2.9999985128489093,
 2.9999984365847507,
 2.9999983584139884,
 2.999998278336622,
 2.9999981963526516,
 2.999998112462077,
 2.999998026664899,
 2.9999979389611164,
 2.99999784935073,
 2.99999775783374,
 2.9999976644101456,
 2.9999975690799476,
 2.9999974718431455,
 2.9999973726997395,
 2.9999972716497294,
 2.9999971686931155,
 2.9999970638298974,
 2.9999969570600755,
 2.9999968483836494,
 2.9999967378006196,
 2.999996625310986,
 16.205128205128204,
 16.41025641025641,
 16.615384615384613,
 16.820512820512818,
 17.025641025641022,
 17.230769230769226,
 17.43589743589743,
 17.641025641025635,
 17.84615384615384,
 18.051282051282044,
 18.25641025641025,
 18.461538461538453,
 18.666666666666657,
 18.87179487179486,
 19.076923076923066,
 19.28205128205127,
 19.487179487179475,
 19.69230769230768,
 19.897435897435884,
 20.102564102564088,
 20.307692307692292,
 20.512820512820497,
 20.7179487179487,
 20.923076923076906,
 21.12820512820511,
 21.333333333333314,
 21.53846153846152,
 21.743589743589723,
 21.948717948717928,
 22.153846153846132,
 22.358974358974336,
 22.56410256410254,
 22.769230769230745,
 22.97435897435895,
 23.179487179487154,
 23.38461538461536,
 23.589743589743563,
 23.794871794871767,
 23.99999999999997,
 24.205128205128176,
 24.41025641025638,
 24.615384615384585,
 24.82051282051279,
 25.025641025640994,
 25.230769230769198,
 25.435897435897402,
 25.641025641025607,
 25.84615384615381,
 26.051282051282016,
 26.25641025641022,
 26.461538461538424,
 26.66666666666663,
 26.871794871794833,
 27.076923076923038,
 27.282051282051242,
 27.487179487179446,
 ...]

In [0]:
sub=test['2020-04-10':]

In [0]:
sub['target']=predictions

In [62]:
sub.head()

                 Territory X Date     target       Region       Date
Date
2020-04-10  Afghanistan X 4/10/20  15.192308  Afghanistan 2020-04-10
2020-04-11  Afghanistan X 4/11/20  15.384615  Afghanistan 2020-04-11
2020-04-12  Afghanistan X 4/12/20  15.576923  Afghanistan 2020-04-12
2020-04-13  Afghanistan X 4/13/20  15.769231  Afghanistan 2020-04-13
2020-04-14  Afghanistan X 4/14/20  15.961538  Afghanistan 2020-04-14

In [0]:
sub.to_csv('ss.csv',index=False)

In [43]:
len(test.Region.unique()),len(df.Territory.unique())

(209, 209)